### ISSUE TITLE
No rendering observed

### ISSUE THREAD

**Issue by mkllnk** [n8n-io/discourse-n8n-wf#2]
Hello! And thank you for providing this plugin.

I posted some workflows on a Discourse instance:

* https://community.openfoodnetwork.org/t/n8n-workflows-for-the-discover-regenerative-api/2954

The posts contain code blocks like this:

<pre>
```json
{
  "name": "List producers",
  "nodes": [
    ...
  ]
}
```
</pre>

I installed the plugin following the [official documentation](https://meta.discourse.org/t/install-plugins-in-discourse/19157) by adding it to the app config `containers/app.yml`:

```yml
## The docker manager plugin allows you to one-click upgrade Discourse
## http://discourse.example.com/admin/docker
hooks:
  after_code:
    - exec:
        cd: $home/plugins
        cmd:
          - mkdir -p plugins
          - git clone https://github.com/discourse/docker_manager.git
          - git clone https://github.com/discourse/discourse-voting.git
          - git clone https://github.com/n8n-io/discourse-n8n-wf.git
```

Then I rebuilt the app:

```
./launcher rebuild app
```

But my workflows are still displayed as simple json. There's one instruction I haven't followed yet:

> Make sure you also whitelist the domain your iframes are calling in the admin settings of Discourse.

I was hoping to see error messages trying to access a domain and then find the setting to whitelist it but I'm not there yet. Any idea what's going on?

I'm currently running Discourse 3.3.0.beta2-dev.
